DROP TABLE IF EXISTS ABTESTING;

CREATE TABLE ABTESTING (
	SERVICE_NAME VARCHAR(128) NOT NULL PRIMARY KEY,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'N',
	ENDPOINT VARCHAR(128) NOT NULL,
	WEIGHT SMALLINT NOT NULL DEFAULT 10 );

INSERT INTO ABTESTING (SERVICE_NAME, ACTIVE, ENDPOINT, WEIGHT) VALUES
('account-service', 'Y', 'http://localhost:2021', 5);

