CREATE TABLE LICENSES (
	LIC_ID VARCHAR(16) NOT NULL PRIMARY KEY,
	PRODUCT_NAME VARCHAR(32) NOT NULL,
	LIC_TYPE VARCHAR(32) NOT NULL,
	ORG_ID VARCHAR(16) NOT NULL
);

INSERT INTO LICENSES (LIC_ID, PRODUCT_NAME, LIC_TYPE, ORG_ID ) VALUES
('A001', 'TV', 'LIC-A', 'ORG001'),
('B001', 'LAPTOP', 'LIC-B', 'ORG002'),
('B002', 'KEYBOARD', 'LIC-A', 'ORG002');


