CREATE USER 'cubicuser'@'localhost' IDENTIFIED BY 'passw0rd';
GRANT ALL PRIVILEGES ON springcloud_db.* TO 'cubicuser'@'localhost' WITH GRANT OPTION;

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
		CUST_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
		CUST_NO CHAR(12) NOT NULL,
		NAME VARCHAR(32) NOT NULL,
		EMAIL VARCHAR(32) NOT NULL,
		ADDRESS VARCHAR(128) );

INSERT INTO CUSTOMER ( CUST_NO, NAME, EMAIL, ADDRESS ) VALUES
('C00000000001', 'John Smith', 'john.smith@gmail.com', '100 Yonge St.'),
('C00000000002', 'Mary Poppins', 'mary.poppins@gmail.com', '200 Yonge St.');

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
		ACCT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
		CUST_ID INT NOT NULL,
		ACCT_NO CHAR(12) NOT NULL,
		ACCT_TYPE CHAR(1) NOT NULL,
		BALANCE DECIMAL(10,2) DEFAULT 0.0,
		FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID)
	);

DROP TABLE IF EXISTS TRANSACTION;
CREATE TABLE TRANSACTION (
		TRX_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
		ACCT_ID INT NOT NULL,
		TRX_TYPE CHAR(2) NOT NULL,	-- DE-Deposit, WD-Withdraw, IN-Interest, ID-Initial Deposit, BP-Bill Payment, TI-Transfer In, TO-Transfer Out 
		AMOUNT DECIMAL(10,2) DEFAULT 0.0,
		FOREIGN KEY (ACCT_ID) REFERENCES ACCOUNT(ACCT_ID)
	);

INSERT INTO ACCOUNT ( CUST_ID, ACCT_NO, ACCT_TYPE, BALANCE ) VALUES
(1, 'SAV-00000001', 'S', 1000.23),
(1, 'CHQ-00000002', 'C', 123.21);

INSERT INTO TRANSACTION ( ACCT_ID, TRX_TYPE, AMOUNT ) VALUES
(1, 'ID', 1000),
(1, 'IN', .23),
(2, 'DE', 100.0),
(2, 'BP', 10),
(2, 'DE', 33.21);

