CREATE USER 'cubicuser'@'localhost' IDENTIFIED BY 'passw0rd';
GRANT ALL PRIVILEGES ON springcloud_db.* TO 'cubicuser'@'localhost' WITH GRANT OPTION;

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
		CUST_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
		CUST_NO CHAR(12) NOT NULL,
		NAME VARCHAR(32) NOT NULL,
		EMAIL VARCHAR(32) NOT NULL,
		ADDRESS VARCHAR(128) );

INSERT INTO CUSTOMER ( CUST_NO, NAME, EMAIL, ADDRESS ) VALUES
('C00000000001', 'John Smith', 'john.smith@gmail.com', '100 Yonge St.'),
('C00000000002', 'Mary Poppins', 'mary.poppins@gmail.com', '200 Yonge St.');
