CREATE TABLE COURSE (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL );


CREATE TABLE ACCOUNT (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL,
	BALANCE DECIMAL(7,2) DEFAULT 0.0 );

CREATE TABLE TRANSACTION (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ACCOUNT_ID INT NOT NULL,
	TYPE CHAR(1) NOT NULL,
	AMOUNT DECIMAL(7,2),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID));

INSERT INTO ACCOUNT (NAME, BALANCE) VALUES
('Chequing', 1000 ),
('Saving', 0.0 );

INSERT INTO TRANSACTION (ACCOUNT_ID, TYPE, AMOUNT) VALUES
(1, 'D', 1000),
(2, 'D', 100),
(2, 'W', 100);
